const decisions = [
  {
    id: 1,
    title: "Startup",
    time: "High",
    risk: "High",
    payoff: "High",
    flexibility: "Medium",
  },
  {
    id: 2,
    title: "Job",
    time: "Medium",
    risk: "Low",
    payoff: "Medium",
    flexibility: "Low",
  },
  {
    id: 3,
    title: "Learn React",
    time: "Medium",
    risk: "Low",
    payoff: "Medium",
    flexibility: "High",
  },
  {
    id: 4,
    title: "Learn DSA",
    time: "High",
    risk: "Medium",
    payoff: "High",
    flexibility: "Medium",
  },
  {
    id: 5,
    title: "MBA",
    time: "High",
    risk: "Medium",
    payoff: "High",
    flexibility: "Low",
  },
  {
    id: 6,
    title: "Mtech",
    time: "High",
    risk: "Medium",
    payoff: "Medium",
    flexibility: "Low",
  },
  {
    id: 7,
    title: "Invest in Stocks",
    time: "Low",
    risk: "Medium",
    payoff: "Medium",
    flexibility: "High",
  },
  {
    id: 8,
    title: "Crypto",
    time: "Low",
    risk: "High",
    payoff: "High",
    flexibility: "High",
  },
  {
    id: 9,
    title: "Learn Web Dev",
    time: "Medium",
    risk: "Low",
    payoff: "Medium",
    flexibility: "High",
  },
  {
    id: 10,
    title: "Learn AI/Ml",
    time: "High",
    risk: "Medium",
    payoff: "High",
    flexibility: "Medium",
  },
];

export default decisions;
